### PR TITLE
Feature/hamburger

### PR DESCRIPTION
**Pull request by elkcityhazard**
add a few different sizes for the blob bg image
remove h1 for hamburger menu
add button
add accessibility features for hamburger button

### CODE REVIEW

**Comment by oklopfer** [comment]
I dont understand the new sizes for the blob image. The whole point with css is we don't need those

**Comment by elkcityhazard** [comment]
@oklopfer  the original blob is 8k wide I believe and over 3.5mb.  Why do you need to load an 8k wide image on a tablet or a cellphone that will want the lowest available resource size when a 499px wide image will do just as well?  typically you'd use css image-set property to dynamically load the appropriate image per viewport,  Since this is tailwind I  opted to just inline the images  via  tailwind.  

I often use homepages to get to documentation when I am doing stuff in the field.  Having a 3.5mb image block the content from loading is just bad frontend practice.  Since the image is called from the css, you can't lazy load it or  decode it in an async way as far as I know.  I'm often in server rooms where wifi is obstructed and 3g is about the best speed I get.  

The point of css is to dynamically adapt resources for screens.  Having resources that aren't specifically optimized for designated breakpoints is just garbage in, garbage out in terms performance I feel.

**Comment by oklopfer** [comment]
So then reduce the image size. Don't make more clutter.

**Comment by elkcityhazard** [comment]
noted.

**Pull request closed without merging**
